version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    docker:
      - image: circleci/node:10.15.1-browsers
        environment:
          CHROME_PATH: /usr/bin/google-chrome
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run start
            - run: npm test
            - run: npm run test:pa11y
workflows:
  build-and-test:
    jobs:
      - build-and-test
